sudo: required
language: java
services:
- docker
cache:
  directories:
  - "$HOME/.m2"
  - "$TRAVIS_BUILD_DIR/node_modules"
jdk:
- oraclejdk8
env:
  global:
  - secure: AgVMUXaAb/XM+NmJOaXwyd6u5OKDflvm2SY+QAyAz5VKkI4tDuaPVKOTJ+bAy5gR2Y7naOwCAot2ucLsDnx2NYCh5G6EfLtdF5sH1YD/ZBcCne+ySsSRSQZulJ+7wyNCCCSW1nXzAehq/fVZP4K86KtAGYS+C0OvrCoQx3v69AeqFJmypNBtMdrdXqrEwCb21tRbdOe8vhXMAk2VLtUIvDyj2ZYONaCxoiI70XGSdj3r3gtc3gXpCq0fBWLo3KXhYVlkr9YdLtIBgx/mwvs1CWOS+U9iDn1537/Ag/h4fIZx/wb1EUl/hXnwpX2sUBYp0b7Oy32uhxVni4pPHbAtGUSkUol878jq2chOC3OTR1YD97e27ebZiIWxThdfgC9TpHMwyplb6rjqCVZXczWxJ2qBzoHdmQBwqSqNJJhmwAUQkHGvkA7lz3CPvAubLnPRR9gqmPPY2aWSlCw9xlENcLxnkJom4lkxFTz8FwKnLskGOyJeoETPyeD/wHR/pULj7DzNTMRDhCsZID1vSuEDPi5xeCzZs3WgZvRt/EX4K5LNfo2mstuCfIf5wF77duWrbRaNLhsfQt006UbcwsyOeXLipJcLL+0sZ9yzdJ0fGN/a8ByMxq26rnZunULLZ/8zglxeUPfkQLVG6mHTCpOHiR9D1bLsYRFXFRDYa6/rDr0=
  - secure: Tg/OWV+TixAEomzVmxxckqshmtVZTCbEHdozwsdpeOnxEf92NVcfLFLxto31ln4sY/RfcAF7V7f3ePa9KHnbCXx8AsNdmPzFwA3cB7jNVVBxS0dqMBSm63FjNApkIkty3LB9YNpCyRe6eu9cEBXwoXo6Ls9XoINcWKYzqlhiv8Kx1hXsyD2sV7D31lY3MirsVbbTu6+0jxRCyRM0w9NUWWXuEV83NpMuJwKGzvqTROELghW6CNvRXENZON1f0m7udKlCB0uC9VwRtZoKXqmfJ5bk9OntWF2YggEEZ5jBRhPDLRXTSx0EI0DoXZc1bhBfQWK5ZRsShFHvVZVRl7YLrKe7GaIf6ITm0I9WdIY6X5dZu5DoJ/v//+0sncowQTQPZ0YsM1GhwDoFGSvZfo5Mr3423EogYlFU9nrBsx4DrxlxHdEMwB69yWvyHfY4GeVpypjryeuCo1gLLtjPt1BQP2V9ixd4ixZLdqqI1a9QK1TJgRjtxQdQY9zDFQgurcrQj8lnzYB7bhiO2DTf+9pm7irJgessI8jNHNPnuHk+HQWbSn9MTmENRIGhDlm7I0+iXT2y33F/F9bqJR7dSUT1w1gULdsif5S+lmfMsFgPqnZziiExroScefjXqzOkDqqGM4mGhNyVcaKux0rXXo+7GsjKkgodF9rvF6p2D08fMqQ=
  - SECRATDOCKERREPO=securityrat/securityrat
before_install:
- sudo apt-get update
- sudo curl -sL https://deb.nodesource.com/setup_8.x | sudo bash
- sudo apt-get install nodejs
- sudo apt-get install build-essential
- sudo npm install -g bower grunt-cli
stages:
- test
- name: deploy
  if: branch = master
jobs:
  include:
  - stage: test
    script:
    - mvn test
  - stage: deploy
    script:
    - mvn -Pprod -DskipTests package
    - export WAR_FILE="$(ls target/ | egrep .*\.war$)"
    - export NAME="$(echo $WAR_FILE | egrep -oh '(.*)[^\.war]')"
    - export TAG_NAME=$(git describe --exact-match)
    - chmod +x createArchive.sh
    - "./createArchive.sh"
    before_deploy:
    - export RELEASE_ZIP_FILE=$(ls target/*.zip)
    - export RELEASE_TAR_FILE=$(ls target/*.tar.gz)
    deploy:
      provider: releases
      api_key:
        secure: T2Blmetw45MKwt9nmERqfjw9XwKeZVRXXg/JeW1mHOwr9UDn7L93MAItGEmMq0UdGB+mj49JyNys2Gz2PO5D8fnFVAqcXolbjJ7DprGW8Ha7ghUSHPYuHaJRZC+87f08+tRoNP4bYVpFG/HOr2km7lfuTxnpK+fnEdY+tkTBvMYsNMwyKUzHezXXpeiY8nULfsj2Mxgpuj6J0e7Wv/tYgXaGME6jn3czko5Zpu/7fVTFz5xuXc7C+ULx8WTEBm3XKBYOT4bM3j4qV2VyNXeTdcLi2tj1XOLswch2U73NBGaBnAlLkch/Hp2uSkY25+ajQzyBid5bM5bCI8xISta7cUNdxQQ83ER1xele1y3m5PlC9rGxgz1VEjBkn3rgf0797l11z6xohre54MpZYsCtjKXFy1qs8bURmmxyufMXmBamJMWYH+Ven6gAqIZudo8nF0iSATzvffvTEZ2/7Gm3kQ2RFYUsqpXgxxi7LikuDnyvsOBb4mU/HTzYyDKmnxYU/cazDJw9pPryUZerFJg48IpP4dKtievafFxPVJbf/KE3MZCwp6oqB8E1g7BJg72IdmWWGP3XINkTb72l5vL70aR7YvxfRDwRb6tnu0V6xyCkNXxy/6RHNuCwKrHFdXamK/U3Q9hjfDRE6W9GRp/8kagh6TKGx0Spu5rOJU7NQ5U=
      skip_cleanup: true
      file_glob: true
      file:
      - "${RELEASE_ZIP_FILE}"
      - "${RELEASE_TAR_FILE}"
      on:
        repo: SecurityRAT/SecurityRAT
        branch: master
        condition: "-n $TAG_NAME"
    after_deploy:
    - chmod +x afterDeploy.sh
    - "./afterDeploy.sh"

