language: java
jdk:
- oraclejdk8
before_install:
- sudo apt-get update
- sudo apt-get install -y nodejs
- curl -L https://www.npmjs.com/install.sh | sh
- npm install bower
- npm install grunt-cli
script:
- mvn -Pprod package
- chmod +x createArchive.sh
- "./createArchive.sh"
branches:
  only:
  - master
