sudo: required
language: java
services:
- docker
cache:
  directories:
  - "$HOME/.m2"
  - "$TRAVIS_BUILD_DIR/node_modules"
jdk:
- oraclejdk8
env:
  global:
  - secure: FgbCfmfQbsRjZ7uc9d3aQYYzTKPeBu8cD9tgJt/RKOazAC1k4x0PiKT7dvy4eYwCY/Ld22JqMy+FweFcMSoCAb0R7AeopsSr26qneQ6NA7qQET1g6uTiHksv0mxxOvAd5b8G27dqfcwGa7ocUeV1qnAM5MaI6iROK9KkK8edtpezhLN7vrKs9ugeJjk3HvcLu64OOkHJt8ZMqeljtmhbKH90VpzNaF/KsMZ01Tp6E0SmVQU6e4guiP/xhSY9W+vPsALmtDY6rcll0wioPo+FFmIZCw/LQMmVwDP5s6q98oSIcPll/a0b155yYHyYalMgGZJJ2vKKxWWZEp2XE3StmRzcxwO+PZwmfWnY4vMKHKecbV4mNUcUHiYlekuXhn8F8H7bgCO20SvDSDHRZwbYokXPN771J35B5ShGZ8GN6j9dr/2fXMg4w5ZQqavxzBCl5c+AkwpPLBiCL0JTFqQvsNHLqrCMm8hkT8ydZ2fw1nuA8WCLWDYHHlhIDolTyYBx5Qf18Gc5/oeLDyGY4s/mg4VEE5Lmd791XFPvTtu525iuCtQYKda6HbzITX5v4If5EYLYkgpb0e+ma0B8otwe4xolGrkmbb7hTXAj3vlZVwH7mPw5BGTzGvxFmo3YvGZujetHJEwqF+NktsGI4ikwwk+RFdJBqZmpVEF0+s0II0U=
  - secure: Wzbb/OmqKuBjFLf4d4ealvZHYsi0kD2PLj9klD6Ttb8NswQ75ph9cNm7ps09AffWAMr2obYOWCa6BaUS667emLAe4BmHjhep7MOQBFOsP9E0lXBhyB2uafb+TEyghipcVxezRqKCaLzEPv6wLuz327IiqTGtvYaIy5D4yk2aZ7Kvlo4Q7v4oXD5vHkvGljSPOlo879gv2h8ndKF8kF2VFYVHCLpmVifkX5XsYuk9OhPval43oZxMfgLWiiLJ/4qF7kuHCOBLnLzNrTuyq9eDafT0od9xiXs+imqv0j4KN/CAubr0g3jr4ntiHcNs1h/eys3a2qE1ZghjyLznwhBEWE/CcYmlmIQ6Jf+ga9lWwp5UKn52/+Ixhv82DgTe5JwtNYrG2yFfxnbl9Ekg6/PPmsbsTuHyWFztDPsp5+6qhBRDlvkPrM04a5h1mpSzioQidbrmS1eIFo8wRPLKrfmS6fxgKPw8vPLxyMY4M3uY5+udhA22Fc74ZhSpXu7zaNDAPh9h4ZcOj3s8+oIo5595ozQoUJtQ+iSKdDoUZbnZLGD5cw/X9tI4sWB1RiS2L/b658cYPCi5d7j+3NyYV0JpqqaysetsGjEPAG/akilpJU1QlUGDCaUTVXWR89dONHv6ap/sFbckNIa0aC++pYUpS3ye6Ljwdfx9iRVlhzssFCM=
  - SECRATDOCKERREPO: securityrat/securityrat
before_install:
- sudo apt-get update
- sudo curl -sL https://deb.nodesource.com/setup_4.x | sudo bash
- sudo apt-get install nodejs
- sudo apt-get install build-essential
- sudo npm install -g bower grunt-cli
script:
- mvn -Pprod package
- export WAR_FILE="$(ls target/ | egrep .*\.war$)"
- export NAME="$(echo $WAR_FILE | egrep -oh '(.*)[^\.war]')"
- export TAG_NAME=$(git describe --exact-match)
- chmod +x createArchive.sh
- "./createArchive.sh"
branches:
  only:
  - master
before_deploy:
- export RELEASE_ZIP_FILE=$(ls target/*.zip)
- export RELEASE_TAR_FILE=$(ls target/*.tar.gz)
deploy:
  provider: releases
  api_key:
    secure: T2Blmetw45MKwt9nmERqfjw9XwKeZVRXXg/JeW1mHOwr9UDn7L93MAItGEmMq0UdGB+mj49JyNys2Gz2PO5D8fnFVAqcXolbjJ7DprGW8Ha7ghUSHPYuHaJRZC+87f08+tRoNP4bYVpFG/HOr2km7lfuTxnpK+fnEdY+tkTBvMYsNMwyKUzHezXXpeiY8nULfsj2Mxgpuj6J0e7Wv/tYgXaGME6jn3czko5Zpu/7fVTFz5xuXc7C+ULx8WTEBm3XKBYOT4bM3j4qV2VyNXeTdcLi2tj1XOLswch2U73NBGaBnAlLkch/Hp2uSkY25+ajQzyBid5bM5bCI8xISta7cUNdxQQ83ER1xele1y3m5PlC9rGxgz1VEjBkn3rgf0797l11z6xohre54MpZYsCtjKXFy1qs8bURmmxyufMXmBamJMWYH+Ven6gAqIZudo8nF0iSATzvffvTEZ2/7Gm3kQ2RFYUsqpXgxxi7LikuDnyvsOBb4mU/HTzYyDKmnxYU/cazDJw9pPryUZerFJg48IpP4dKtievafFxPVJbf/KE3MZCwp6oqB8E1g7BJg72IdmWWGP3XINkTb72l5vL70aR7YvxfRDwRb6tnu0V6xyCkNXxy/6RHNuCwKrHFdXamK/U3Q9hjfDRE6W9GRp/8kagh6TKGx0Spu5rOJU7NQ5U=
  skip_cleanup: true
  file_glob: true
  file:
  - "${RELEASE_ZIP_FILE}"
  - "${RELEASE_TAR_FILE}"
  on:
    repo: SecurityRAT/SecurityRAT
    branch: master
    condition: "-n $TAG_NAME"
after_deploy:
- chmod +x afterDeploy.sh
- "./afterDeploy.sh"
