version: '3'
services:
  mysql-service:
    network_mode: bridge
    container_name: securityrat_mysql3
    build:
      context: ./mysql
    image: gcr.io/code-intelligence/securityrat_mysql
    environment: 
      MYSQL_DATABASE: 'securityrat'
      MYSQL_ROOT_PASSWORD: 'changeit'
      MYSQL_USER: 'user' # This user has full priviledge over the MYSQL_DATABASE
      MYSQL_PASSWORD: 'password' # Password of the MYSQL_USER
    command: mysqld --skip-ssl
