version: '3'
services:
  mysql-service:
    networks:
      - ci-fuzzing
    container_name: securityrat_mysql
    build:
      context: ./mysql
    image: gcr.io/code-intelligence/securityrat_mysql
    environment: 
      MYSQL_DATABASE: 'securityrat'
      MYSQL_ROOT_PASSWORD: 'changeit'
      MYSQL_USER: 'user' # This user has full priviledge over the MYSQL_DATABASE
      MYSQL_PASSWORD: 'password' # Password of the MYSQL_USER
    command: mysqld --skip-ssl
    ports:
      - "0.0.0.0:3306:3306"
      - "0.0.0.0:33060:33060"
networks:
  ci-fuzzing:
    external:
      name: ci-fuzzing