name: Testing app and packaging

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install NPM modules
        run: npm install bower grunt
      - name:  Build with maven
        run: mvn --batch-mode --update-snapshots verify

  test docker packaging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: docker build -f .docker/app
